require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'bin/*' # don't worry about binstubs
    - '.git/**/*'
    - 'vendor/**/*' # where github action stores cached bundle
    - 'spec/fixture_specs/**/*'

RSpec/DescribedClass:
  EnforcedStyle: explicit

RSpec/ExampleLength:
  Max: 10

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleMemoizedHelpers:
  Max: 10
