name: Tests & Linting
on: pull_request
permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
      - name: rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          skip_install: true # use bundler
          use_bundler: true
          rubocop_flags: '--config .rubocop.yml'
          fail_on_error: true
  rspec-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.6
          - 2.7
          - '3.0'
          - 3.1
        gemfile:
          - 3.5
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
          - 3.11
          - 3.12
    env:
      BUNDLE_WITHOUT: 'development'
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rspec-${{ matrix.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: |
          bundle exec rspec \
            --format json --out tmp/rspec.json \
            --format documentation
      - name: Upload test results to Captain
        uses: rwx-research/upload-captain-artifact@v1
        if: ${{ matrix.ruby == 3.1 && matrix.gemfile == 3.12 && always() }}
        continue-on-error: true
        with:
          artifacts: |
            [
              {
                "name": "RSpec",
                "path": "tmp/rspec.json",
                "kind": "test_results",
                "parser": "rspec_json"
              }
            ]
          job-matrix: ${{ toJSON(matrix) }}
          captain-token: ${{ secrets.RWX_ACCESS_TOKEN }}

  # strategy borrowed from https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
  # this is used to summarize the matrix results into a single job (abq-work) that can be used as a required check
  rspec-github-workflow-wrapup-helper:
    needs: rspec-matrix # run after shards
    runs-on: ubuntu-latest
    if: success() # only run when matrix passed
    # store success output flag for ci job
    outputs:
      success: ${{ steps.setoutput.outputs.success }}
    steps:
      - id: setoutput
        run: echo "::set-output name=success::true"
  rspec:
    runs-on: ubuntu-latest
    if: always() # always run, so we never skip the check
    needs: rspec-github-workflow-wrapup-helper
    steps:
      # pass step only when output of previous after-shards job is set
      # in case at least one of the shard fails, after-shards is skipped
      # and the output will not be set, which will then cause the ci job to fail
      - run: |
          passed="${{ needs.rspec-github-workflow-wrapup-helper.outputs.success }}"
          if [[ $passed == "true" ]]; then
            echo "Shards passed"
            exit 0
          else
            echo "Shards failed"
            exit 1
          fi
  nixfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - run: nix fmt -- --check flake.nix
  abq-test-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        ruby:
          - 2.6
          - 3.1
        gemfile:
          - 3.5
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
          - 3.11
          - 3.12
    env:
      BUNDLE_WITHOUT: 'development'
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rspec-${{ matrix.gemfile }}.gemfile
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: setup ruby & bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup abq
        uses: rwx-research/setup-abq@v1
        with:
          access-token: ${{ secrets.RWX_ACCESS_TOKEN }}
      - name: start abq test
        # we run the test and then compare the output to a file checked into the repo
        # the first line of the test includes the run id, so we slice it off
        # the last line of the test includes the time to run tests, which is flakey, so we slice it off
        run: |
          bundle exec rspec \
            --format json --out tmp/rspec.json \
            --format documentation \
            abq_spec
        shell: bash
        env:
          RUN_ID: ${{github.run_id}}-${{github.run_attempt}}-${{matrix.ruby}}-${{matrix.gemfile}}
          ABQ_LOG: ${{ runner.debug && 'debug' || 'info' }}
          ABQ_API_KEY: ${{ secrets.RWX_ACCESS_TOKEN }}

  # strategy borrowed from https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
  # this is used to summarize the matrix results into a single job (abq-work) that can be used as a required check
  abq-test-github-workflow-wrapup-helper:
    needs: abq-test-matrix # run after shards
    runs-on: ubuntu-latest
    if: success() # only run when matrix passed
    # store success output flag for ci job
    outputs:
      success: ${{ steps.setoutput.outputs.success }}
    steps:
      - id: setoutput
        run: echo "::set-output name=success::true"
  abq-test:
    runs-on: ubuntu-latest
    if: always() # always run, so we never skip the check
    needs: abq-test-github-workflow-wrapup-helper
    steps:
      # pass step only when output of previous after-shards job is set
      # in case at least one of the shard fails, after-shards is skipped
      # and the output will not be set, which will then cause the ci job to fail
      - run: |
          passed="${{ needs.abq-test-github-workflow-wrapup-helper.outputs.success }}"
          if [[ $passed == "true" ]]; then
            echo "Shards passed"
            exit 0
          else
            echo "Shards failed"
            exit 1
          fi
  abq-work-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        shard: ['1', '2']
        ruby:
          - 2.6
          - 3.1
        gemfile:
          - 3.5
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
          - 3.11
          - 3.12
    env:
      BUNDLE_WITHOUT: 'development'
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rspec-${{ matrix.gemfile }}.gemfile
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: setup ruby & bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Setup abq
        uses: rwx-research/setup-abq@v1
        with:
          access-token: ${{ secrets.RWX_ACCESS_TOKEN }}
      - name: start abq work
        # abq work _should_ fail because we have failing tests, but we want to ensure it only has a single line of output
        run: |
          echo "run worker"
          abq work --run-id "$RUN_ID-success" -n cpu-cores 2>&1 |
            bin/test-worker-output.rb
          set +e
          abq work --run-id "$RUN_ID-failure" -n cpu-cores 2>&1 |
            bin/test-worker-output.rb
        env:
          RUN_ID: ${{github.run_id}}-${{github.run_attempt}}-${{matrix.ruby}}-${{matrix.gemfile}}
          ABQ_LOG: ${{ runner.debug && 'debug' || 'info' }}
          ABQ_API_KEY: ${{ secrets.RWX_ACCESS_TOKEN }}
  # strategy borrowed from https://brunoscheufler.com/blog/2022-04-09-the-required-github-status-check-that-wasnt
  # this is used to summarize the matrix results into a single job (abq-work) that can be used as a required check
  abq-work-github-workflow-wrapup-helper:
    needs: abq-work-matrix # run after shards
    runs-on: ubuntu-latest
    if: success() # only run when matrix passed
    # store success output flag for ci job
    outputs:
      success: ${{ steps.setoutput.outputs.success }}
    steps:
      - id: setoutput
        run: echo "::set-output name=success::true"
  abq-work:
    runs-on: ubuntu-latest
    if: always() # always run, so we never skip the check
    needs: abq-work-github-workflow-wrapup-helper
    steps:
      # pass step only when output of previous after-shards job is set
      # in case at least one of the shard fails, after-shards is skipped
      # and the output will not be set, which will then cause the ci job to fail
      - run: |
          passed="${{ needs.abq-work-github-workflow-wrapup-helper.outputs.success }}"
          if [[ $passed == "true" ]]; then
            echo "Shards passed"
            exit 0
          else
            echo "Shards failed"
            exit 1
          fi
  yard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
      - run: bin/check_yard
